jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Pull and restart Docker container
        run: |
          docker pull your-image:latest
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 80:8080 your-image:latest
      
      - name: Health check
        run: |
          curl -f http://localhost:8080/health || exit 1
