name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh user@your-server "docker pull your-image:latest && docker stop app || true && docker rm app || true && docker run -d --name app -p 80:8080 your-image:latest"
      
      - name: Health check
        run: |
          curl -f http://your-server/health || exit 1
