name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Compile Java classes
        run: |
          mkdir -p HelloWorldJava/out/production/com
          javac -classpath "HelloWorldJava/lib/*" -d HelloWorldJava/out/production/com HelloWorldJava/src/com/*.java

      - name: Archive compiled classes
        run: |
          cd HelloWorldJava/out/production
          tar czf compiled_classes.tar.gz com

      - name: Copy compiled classes to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: HelloWorldJava/out/production/compiled_classes.tar.gz
          target: ~/app/out/production/

      - name: Deploy and build Docker on VM via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd ~/app
            mkdir -p out/production
            tar xzf out/production/compiled_classes.tar.gz -C out/production/
            docker stop app || true
            docker rm app || true
            docker build -t helloworldjava:latest HelloWorldJava/
            docker run -d --name app -p 80:8080 helloworldjava:latest
