name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t helloworldjava:latest .

      - name: Stop and remove existing container (if any)
        run: |
          docker stop app || true
          docker rm app || true

      - name: Run Docker container
        run: |
          docker run -d --name app -p 80:8080 helloworldjava:latest

      - name: Health check
        run: |
          curl -f http://localhost:80/health || exit 1
