name: CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Compile Java sources
        run: |
          javac -d HelloWorldJava/out/production $(find HelloWorldJava/src -name "*.java")

      - name: Tar compiled classes
        run: |
          tar czf HelloWorldJava/out/compiled_classes.tar.gz -C HelloWorldJava/out/production .

      - name: Copy compiled classes to Azure VM
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          source: "HelloWorldJava/out/compiled_classes.tar.gz"
          target: "~/app"

      - name: Copy Dockerfile to Azure VM
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          source: "./HelloWorldJava/Dockerfile"
          target: "~/app/HelloWorldJava"
          strip_components: 2



      - name: Check uploaded files on server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          script: |
            echo "Checking if compiled_classes.tar.gz exists on the server..."
            ls -R

      - name: SSH and deploy with Docker
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          script: |
            set -e
            cd ~/app/HelloWorldJava
            echo "Unpacking compiled classes..."
            mkdir -p production
            tar xzf out/compiled_classes.tar.gz -C production
            echo "Creating image backup if it exists..."
            if docker image inspect helloworldjava:latest > /dev/null 2>&1; then
              docker tag helloworldjava:latest helloworldjava:backup
              echo "Image backup saved as helloworldjava:backup"
            else
              echo "No image to back up. This may be the first deployment."
            fi
            echo "Stopping and removing old container..."
            docker stop app || true
            docker rm app || true
            echo "Building new image..."
            docker build -t helloworldjava:latest .
            echo "Starting new container..."
            docker run -d --name app -p 80:8080 helloworldjava:latest

      - name: Health check (CLI)
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          script: |
            echo "Running health check..."
            docker exec app java -cp /app/out com.Main --health-check

      - name: Rollback if health check fails
        if: failure()
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          script: |
            echo "Health check failed. Starting rollback..."
            docker stop app || true
            docker rm app || true
            if docker image inspect helloworldjava:backup > /dev/null 2>&1; then
              echo "Restoring from backup..."
              docker run -d --name app -p 80:8080 helloworldjava:backup
              echo "Rollback completed successfully."
            else
              echo "No backup image available. Rollback skipped."
            fi

