name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Compile Java classes
        run: |
          mkdir -p out/production/com
          javac -d out/production/com HelloWorldJava/src/com/*.java
          tar -czf out/production/compiled_classes.tar.gz -C out/production com

      - name: Copy compiled classes to VM via SCP
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          source: "out/production/compiled_classes.tar.gz"
          target: "~/app"

      - name: Run deployment script on VM via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          script: |
            cd ~/app
            mkdir -p out/production
            tar xzf out/production/compiled_classes.tar.gz -C out/production/
            docker stop app || true
            docker rm app || true
            docker build -t helloworldjava:latest HelloWorldJava/
            docker run -d --name app -p 80:8080 helloworldjava:latest
