name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t helloworldjava:latest HelloWorldJava/HelloWorldJava

      - name: Tag and push Docker image
        run: |
          docker tag helloworldjava:latest ${{ secrets.DOCKER_USERNAME }}/helloworldjava:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/helloworldjava:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh user@your-server "docker pull ${{ secrets.DOCKER_USERNAME }}/helloworldjava:latest && docker stop app || true && docker rm app || true && docker run -d --name app -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/helloworldjava:latest"

      - name: Health check
        run: |
          curl -f http://your-server/health || exit 1
