name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # lub twój self-hosted runner label

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t helloworldjava:latest

      - name: Stop and remove old container if exists
        run: |
          docker stop app || true
          docker rm app || true

      - name: Run new container
        run: docker run -d --name app -p 80:8080 helloworldjava:latest .

      - name: Health check
        run: |
          curl -f http://localhost:8080/health || exit 1
