name: CI Pipeline

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Compile sources
        run: |
          mkdir -p out
          javac -d out $(find com -name "*.java")

      - name: Compile tests
        run: |
          mkdir -p out/test
          javac -classpath "lib/*:out" -d out/test $(find test -name "*.java")

      - name: Run tests
        run: |
          java -jar lib/junit-platform-console-standalone-1.10.2.jar \
            -cp out:test \
            --scan-classpath --details tree
