name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21
        
    - name: Run Checkstyle
      run: |
        java -jar HelloWorldJava/lib/checkstyle-10.26.1-all.jar \
        -c HelloWorldJava/lib/google_checks.xml \
        HelloWorldJava/src HelloWorldJava/Test
      
    - name: Compile source code
      run: |
        mkdir -p out/production
        javac -classpath "HelloWorldJava/lib/*" -d out/production $(find HelloWorldJava/src -name "*.java")

    - name: Compile tests
      run: |
        mkdir -p out/test
        javac -classpath "HelloWorldJava/lib/*:out/production" -d out/test $(find HelloWorldJava/Test -name "*.java")

    - name: Run tests
      run: |
        java -jar HelloWorldJava/lib/junit-platform-console-standalone-1.10.2.jar \
          -cp out/production:out/test \
          --scan-classpath --details tree
