name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21

    - name: Download Checkstyle jar
      run: wget -O checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.26.1/checkstyle-10.26.1-all.jar

    - name: Download Google Checks config
      run: wget -O google_checks.xml https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml

    - name: Run Checkstyle
      run: |
        java -jar checkstyle.jar -c google_checks.xml HelloWorldJava/src HelloWorldJava/Test

    - name: Compile source code
      run: |
        mkdir -p HelloWorldJava/out/production/HelloWorldJava
        javac -classpath "HelloWorldJava/lib/*" -d out/production $(find HelloWorldJava/src -name "*.java")

    - name: Compile tests
      run: |
        mkdir -p out/test
        javac -classpath "HelloWorldJava/lib/*:out/production" -d out/test $(find HelloWorldJava/Test -name "*.java")

    - name: Run tests
      run: |
        java -jar HelloWorldJava/lib/junit-platform-console-standalone-1.10.2.jar \
          -cp out/production:out/test \
          --scan-classpath --details tree
