  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compile tests
        run: |
          mkdir -p out/test
          javac -classpath "HelloWorldJava/lib/*:out" -d out/test $(find HelloWorldJava/Test -name "*.java")

      - name: Compile src
        run: |
          mkdir -p out/production
          javac -classpath "HelloWorldJava/lib/*" -d out/production $(find HelloWorldJava/src -name "*.java")

      - name: Run tests
        run: |
          java -jar HelloWorldJava/lib/junit-platform-console-standalone-1.10.2.jar \
            -cp out/test:out/production \
            --scan-classpath --details tree
