name: CI Pipeline

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compile source
        run: |
          mkdir -p out
          javac -d out $(find src -name "*.java")

      - name: Compile tests
        run: |
          mkdir -p out/test
          javac -classpath "lib/junit-platform-console-standalone-1.10.2.jar:out" -d out/test $(find Test -name "*.java")

      - name: Run tests
        run: |
          java -jar lib/junit-platform-console-standalone-1.10.2.jar \
            --class-path out:out/test \
            --scan-classpath \
            --details tree
